FROM binduwavell/codenvy-alfresco-sdk-2.1.1-community:0.1

MAINTAINER Bindu Wavell <bindu@ziaconsulting.com>

ENV CODENVY_APP_BIND_DIR /home/user/application
VOLUME ["/home/user/application"]

ENV CODENVY_APP_PORT_8080_HTTP 8080
EXPOSE 8080
